name: envelop staging workflow #

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: deploying envelop in staging
        uses: actions/checkout@v3
      - run: echo IO_STAC_CATALOG_URL=${{ secrets.IO_STAC_CATALOG_URL }} >> .env.staging
      - run: echo ACER_STAC_CATALOG_URL=${{ secrets.ACER_STAC_CATALOG_URL }} >> .env.staging
      - run: echo GEOIO_API_SERVER=${{ secrets.GEOIO_API_SERVER }} >> .env.staging
      - run: echo ATLAS_API_SERVER=${{ secrets.ATLAS_API_SERVER }} >> .env.staging
      - run: echo ATLAS_API_PATH=${{ secrets.ATLAS_API_PATH }} >> .env.staging
      - run: echo ATLAS_API_TOKEN=${{ secrets.ATLAS_API_TOKEN }} >> .env.staging
      - run: echo BQ_IMPACTS_GITHUB_TOKEN=${{ secrets.BQ_IMPACTS_GITHUB_TOKEN }} >> .env.staging
      - run: echo GITHUB_USERNAME=${{ secrets.GITHUB_USERNAME }} >> .env.staging
      - run: make build-staging
      - run: make start-staging